import type { Config } from "tailwindcss";

// Design tokens portados de la referencia de Álvaro (sesión de voz inmersiva).
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "on-background": "#e4e1ed",
        "tertiary-fixed": "#ffdcc5",
        "secondary-container": "#03b5d3",
        "on-tertiary-fixed-variant": "#703700",
        "on-error": "#690005",
        primary: "#c0c1ff",
        secondary: "#4cd7f6",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#301400",
        "surface-container-highest": "#34343d",
        "primary-fixed": "#e1e0ff",
        "on-secondary": "#003640",
        "surface-bright": "#393841",
        "primary-fixed-dim": "#c0c1ff",
        error: "#ffb4ab",
        background: "#13131b",
        "inverse-surface": "#e4e1ed",
        "surface-dim": "#13131b",
        "inverse-on-surface": "#303038",
        "outline-variant": "#464554",
        "on-secondary-fixed": "#001f26",
        "on-primary-fixed": "#07006c",
        "surface-variant": "#34343d",
        "secondary-fixed": "#acedff",
        "on-secondary-fixed-variant": "#004e5c",
        "on-tertiary-container": "#452000",
        "on-surface": "#e4e1ed",
        "on-tertiary": "#4f2500",
        "on-secondary-container": "#00424e",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container": "#1f1f27",
        surface: "#13131b",
        "surface-container-lowest": "#0d0d15",
        "surface-container-high": "#292932",
        "on-primary": "#1000a9",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#4cd7f6",
        "primary-container": "#8083ff",
        outline: "#908fa0",
        "on-primary-container": "#0d0096",
        "tertiary-fixed-dim": "#ffb783",
        "surface-container-low": "#1b1b23",
        tertiary: "#ffb783",
        "tertiary-container": "#d97721",
        "inverse-primary": "#494bd6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        gutter: "24px",
        xl: "32px",
        xxl: "48px",
        md: "16px",
        "container-max": "1280px",
        lg: "24px",
      },
      fontFamily: {
        "headline-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-xl": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
